Repository Kuama-IT/kuama_flutter, pull requests merged in 2021-09, with the labels that each got.

#7 Apply flutter lints and update dependencies
  .github/workflows/main.yml
  analysis_options.yaml
  lib/src/features/app_pages/use_cases/open_settings_app_page.dart
  lib/src/features/dio/log_dio_interceptor.dart
  lib/src/features/permissions/bloc/_permission_event.dart
  lib/src/features/permissions/bloc/_permission_state.dart
  lib/src/features/permissions/use_cases/check_permission.dart
  lib/src/features/permissions/use_cases/request_permission.dart
  lib/src/features/permissions/use_cases/update_can_ask_permission.dart
  lib/src/features/permissions/widgets/ask_allow_permission_dialog.dart
  lib/src/features/permissions/widgets/refresh_permission_bloc_listener.dart
  lib/src/features/positioner/bloc/_positioner_event.dart
  lib/src/features/positioner/bloc/_positioner_state.dart
  lib/src/features/positioner/bloc/position_bloc.dart
  lib/src/features/positioner/repositories/position_repository_impl.dart
  lib/src/features/positioner/widgets/ask_enable_position_service_dialog.dart
  lib/src/features/positioner/widgets/localize_position_bloc_builder.dart
  lib/src/features/positioner/widgets/order_active_position_bloc_listener.dart
  lib/src/shared/feature_structure/use_case.dart
  lib/src/shared/utils/locker.dart
  lib/src/shared/widgets/dialogs/app_settings_dialog.dart
  lib/src/shared/widgets/dialogs/block_dialog.dart
  pubspec.lock
  pubspec.yaml
  test/features/permission/permission_bloc_test.dart
  test/features/positioner/positioner_bloc_test.dart
  test/shared/locker_test.dart
Labels: enhancement, size/L

#8 Changed dialog text and settings page destination
  lib/src/features/positioner/widgets/ask_enable_position_service_dialog.dart
  lib/src/shared/widgets/dialogs/app_settings_dialog.dart
Labels: bug, size/M

#9 Update to stable release index_generator
  .idea/runConfigurations/Generate_and_watch_dart_files.xml
  .idea/runConfigurations/Generate_dart_files.xml
  .idea/runConfigurations/Generate_index_files.xml
  lib/kuama_flutter.dart
  lib/src/features/app_pages/repositories/launcher_repository_impl.dart
  lib/src/features/permissions/repositories/permission_repository_impl.dart
  lib/src/shared/library_exports.dart
  lib/src/shared/utils/logger.dart
  lib/src/shared/utils/pretty_formatter.dart
  pubspec.lock
  pubspec.yaml
Labels: enhancement, size/M
